### ISSUE TITLE
Crush on insert Drawer Upgrade

### ISSUE THREAD

**Issue by Krutoy242** [phantamanta44/fluid-drawers#1]
Version: 1.0.0

Steps that lead me to crush:

1. Place Tank
2. Fill it with lava for 4-6 buckets
3. Open interface by `Shift+RMB`
4. Put x13 upgrade in drawer from inventory (by `shift+click` or move with mouse)

[part of debug.log](https://gist.github.com/Krutoy242/64a2551f4e08fad4a390b3a02013a77f)

**Comment by brisingraerowing** [comment]
[My Crash Log](https://gist.github.com/BrisingrAerowing/d1ba3780f7505f29812c66b3f283f3b1)

**Comment by phantamanta44** [comment]
i know why this happens; i'll push a fix as soon as i have the opportunity
