### ISSUE TITLE
[1.0.5] Drawers not holding liquids when broken 

### ISSUE THREAD

**Issue by Targren** [phantamanta44/fluid-drawers#15]
Modpack: "Multiblock Madness"
MC 1.12.2 - Using version Fluid Drawers 1.0.5  and Storage Drawers 5.4.2

B:keepContentsOnBreak=true  in storagedrawers.cfg 

When breaking a "Basic Tank" when it's empty, the item has the "tape" decal on the sides, as Storage Drawers do when they're broken with Keep Contents enabled. However, when breaking a fluid drawer with a fluid in it (tested water and lava), the item has no tape and the contents of the tank are lost.

**Comment by phantamanta44** [comment]
oops, i accidentally flipped the drawer emptiness logic
