### ISSUE TITLE
No output on framing table, alongside framed tank not rendering ontop of table

### ISSUE THREAD

**Issue by Landiie** [phantamanta44/fluid-drawers#3]
Version: 1.0.1
![ezgif-7-1d8ed7bfb175](https://user-images.githubusercontent.com/43101146/93148278-33125700-f6a8-11ea-9a0b-6ffc2c0454ee.gif)

this IS in a modpack fyi

thanks for the update by the way!

**Comment by phantamanta44** [comment]
could I get a log, please?

**Comment by Landiie** [comment]
a full log? there is no crash so i can only share a full log

**Comment by phantamanta44** [comment]
yes

**Comment by Landiie** [comment]
alright, its on [google drive](https://drive.google.com/file/d/15o4CzyOXazP-9S82_ZmmIJj8EOighFaN/view?usp=sharing) since its too big for pastebin sadly, hope thats alright. Thank you again!

**Comment by phantamanta44** [comment]
your storage drawers version is outdated; i don't think that should be an issue, but updating it is worth a try...

**Comment by Landiie** [comment]
5.4.2 is the latest 1.12.2 release, unfortunately

![versions list](https://i.gyazo.com/993ea715da1e64f78b8ed28f16530aa3.png)

**Comment by phantamanta44** [comment]
the log seems to indicate that you're running 5.2.2

**Comment by Landiie** [comment]
huh weird, ill redownload just incase, my multimc instance says different, but just to be certain ill redownload. 
![multimc instance](https://i.gyazo.com/4fcea260a2f05cd0364d504011fe3e62.png)

**Comment by Landiie** [comment]
still no improvement sadly, same issue

**Comment by phantamanta44** [comment]
that's weird. i'll do more investigation later, when i have the time

**Comment by Landiie** [comment]
sure thing! thanks again for looking into it c: 

oddly enough, i rechecked my log and saw that it still says its running 5.2.2, maybe an error on their part?

**Comment by Speecker** [comment]
Confirmed :P Got the same problem.
Awesome Mod So Far 👍
