### ISSUE TITLE
[Feature Request] At least 1 pixel of liquid should be visible

### ISSUE THREAD

**Issue by Krutoy242** [phantamanta44/fluid-drawers#4]
When placing liquid in upgraded drawer there is no indication that it have liquids. Probably, because liquid column relatively too small to form at least 1 pixel of screen space.
If there is any amount of liquids, request it should be always visible 
<img src="https://i.imgur.com/uKdmOoZ.png" width=300>

**Comment by phantamanta44** [comment]
should be fixed upstream in libnine: https://github.com/phantamanta44/libnine/commit/d174b7f7944a5334a1449a86abbfa5f321793e1f
