### ISSUE TITLE
[Request] Make placing and breaking the drawers sounds as iron blocks

### ISSUE THREAD

**Issue by ChromaPIE** [phantamanta44/fluid-drawers#8]
The woody sound is too incongruent as the fluid drawers neither look like woody things nor are made from woody materials.

Please make a change if it is not restricted by other mods.

**Comment by phantamanta44** [comment]
which drawer? the standard metal one makes metallic noises and the framed drawer makes wood noises, which makes sense, i think

**Comment by ChromaPIE** [comment]
Ah well, I was using the framed one. Sorry for that.
