### ISSUE TITLE
Crash on placing down framing table, or using framing table

### ISSUE THREAD

**Issue by Landiie** [phantamanta44/fluid-drawers#9]
just encountered this crash with the latest fluid drawers version, [here is the crash log](https://pastebin.com/WPCzZuvt)

thanks again!

edit: hold on might be my fault, double checking

**Comment by phantamanta44** [comment]
eutro made some breaking api changes in 1.2.4, so you'll need a newer version for the FCD integration to not crash horribly

**Comment by Landiie** [comment]
yes thats exactly what i suspected, checking versions now, seems like my multimc is bugging and showing incorrect versions

edit: yup that was it, the actual version of the mod i was using was 1.2.3 instead of the latest 1.2.7 for Framed Compacting Drawers, Whoops! Sorry for the trouble, thanks for looking though <3
